- ui/src/App.tsx
- ui/src/components/Header/index.tsx
- ui/src/pages/Creation/ThresholdSelection.tsx
- ui/src/pages/Creation/index.tsx
- ui/src/pages/Success.tsx
Some more info when a multisig is created
closes #14 
related but not closing, we can do better #13
> Add dedicated page for creation success

- squid/README.md
> Add more info in squid readme

- ui/.env.example
> Swap wrong env example values

- ui/src/components/ToastBar.tsx
- ui/src/components/ToastContent.tsx
- ui/src/contexts/ToastContext.tsx
- ui/src/hooks/useGetSigningCallback.tsx
- closes #27 
- prevent the error from being closed automatically
> Show multisig errors

- ui/src/components/modals/ChangeMultisig.tsx
- ui/src/pages/Creation/Summary.tsx
Fix a bug introduced in the previous PR and removes a component that isn't needed.
> Remove multisig selection in summary

- ui/src/contexts/AccountNamesContext.tsx
- ui/src/pages/Creation/Summary.tsx
closes #31 
I truncate them (any new one) arbitrarily at 50 char.
I found what I did wrong in my tests, I had spaces in my names, which wrapped correctly on several lines.
> Truncate names and fix their display

- squid/src/processor.ts
- squid/src/util/getMultisigCallId.ts
> Fix duplicate id for multisig calls

- ui/.eslintrc
- ui/src/App.tsx
- ui/src/components/Drawer/Drawer.tsx
- ui/src/components/Drawer/DrawerMenu.tsx
- ui/src/components/Header/index.tsx
- ui/src/components/OptionsMenu.tsx
- ui/src/components/layout/Main.tsx
- ui/src/constants.ts
closes #106
Based it on @Lykhoyda PR so as not to create too many conflicts.
we do have some issues with spacing between our PRs, I'll try to setup eslint so that we have the same style.
- import from React (no *)
- import styled from styled-component
- eslint rules to enforce the previous style
sorry I'm jamming a lot of non related things in 1 PR.. I'll stop there, I think it's manageable to review
> Hide help menu when there's no multisig yet

- packages/ui/src/pages/Help/CustomNode.tsx
- packages/ui/src/pages/Help/Overview.tsx
closes #120  introduced in https://github.com/ChainSafe/Multix/pull/110
> Fix overview not diplaying properly

- package.json
- packages/squid/README.md
- packages/squid/package.json
- packages/squid/src/processorHandlers/handleNewProxies.ts
The main goal here is to switch to `sql-statement-timeout` for 3s instead of `max-response-size 10000` that seems buggy
> Remove max-response-size

- packages/ui/src/components/AccountDisplay.tsx
> fix long names

- .github/workflows/deploy-squid.yaml
- .github/workflows/deploy-ui-cf-pages.yaml
- packages/squid/src/util/Env.ts
Align names and prevent having a console log for polkadot prefix
> Prepare for Polkadot deployment

- packages/ui/src/components/CallInfo.tsx
- packages/ui/src/utils/formatBnBalance.ts
> format long balance

- .github/workflows/deploy-squid-stage.yaml
> Drop tables/test

- packages/squid/.env.example
- packages/squid/README.md
- packages/squid/src/processor.ts
- packages/squid/src/util/Env.ts
Add support for subsquid archives that are not part of the subsquid registry using a new `ARCHIVE_URL` env.
> Allow for non registry subsquid archive

- packages/ui/src/contexts/AccountsContext.tsx
> Fix wrong prefix on chain change

- package.json
> Fix docker:start:all script

- .github/workflows/formating.yaml
- .prettierignore
- package.json
- packages/squid/src/processor.ts
- packages/squid/src/util/Env.ts
> Add gh action to check for prettier

- .github/workflows/deploy-squid-stage.yaml
- packages/ui/src/constants.ts
A good way to play with Polkadot is to check well known multisigs such as the top proposal beneficiaries from Dottreasury https://www.dotreasury.com/dot/
> Enable Polkadot network

- packages/ui/src/hooks/useMultisigProposalNeededFunds.tsx
- packages/ui/src/hooks/useProxyAdditionNeededFunds.tsx
- packages/ui/src/hooks/usePureProxyCreationNeededFunds.tsx
> Early return for undefined api const

- packages/ui/package.json
- packages/ui/src/components/Transactions/TransactionList.tsx
- packages/ui/src/components/modals/ProposalSigning.tsx
- packages/ui/src/pages/Home.tsx
- yarn.lock
> Show and group by date of proposal

- packages/ui/src/components/NetworkSelection.tsx
closes #192 
**Before**
**After**
> Change the height of network dropdown

- packages/ui/src/components/CallInfo.tsx
- packages/ui/src/components/Drawer/DrawerMenu.tsx
- packages/ui/src/components/EasySetup/BatchExtrinsic.tsx
- packages/ui/src/components/Header/index.tsx
- packages/ui/src/components/Transactions/Transaction.tsx
- packages/ui/src/components/library/Button.tsx
- packages/ui/src/components/library/Link.tsx
- packages/ui/src/components/modals/ChangeMultisig.tsx
- packages/ui/src/components/modals/EditNames.tsx
- packages/ui/src/components/modals/ProposalSigning.tsx
- packages/ui/src/components/modals/Send.tsx
- packages/ui/src/pages/Creation/index.tsx
- packages/ui/src/pages/Home.tsx
> update buttons and links

- packages/ui/src/components/AccountEditName.tsx
- packages/ui/src/components/AccountSelection.tsx
- packages/ui/src/components/EasySetup/BalancesTransfer.tsx
- packages/ui/src/components/IdenticonBadge.tsx
- packages/ui/src/components/Transactions/Transaction.tsx
- packages/ui/src/components/WatchedAccounts.tsx
- packages/ui/src/components/library/InputField.tsx
- packages/ui/src/components/library/TextFieldStyled.tsx
- packages/ui/src/components/library/index.tsx
- packages/ui/src/components/modals/ChangeMultisig.tsx
- packages/ui/src/components/modals/EditNames.tsx
- packages/ui/src/components/modals/ProposalSigning.tsx
- packages/ui/src/pages/Creation/NameSelection.tsx
- packages/ui/src/pages/Creation/ThresholdSelection.tsx
- packages/ui/src/styles/App.css
- packages/ui/src/styles/theme.ts
> update inputs styles

- packages/ui/src/pages/Home.tsx
self explanatory, caused a crash if clicking on "send" on the watched account.
try it out, watch DCZyhphXsRLcW84G9WmWEXtAA8DKGtVGSFZLJYty8Ajjyfa
> Don't show 'send' if watched pure

- packages/ui/src/components/library/TextFieldStyled.tsx
- packages/ui/src/pages/Creation/index.tsx
> fix inputs misalignment

- packages/ui/src/pages/Home.tsx
> Fix name overflowing

- packages/ui/src/components/AccountEditName.tsx
> Fix renaming name reset when empty

- packages/ui/src/components/OptionsMenu.tsx
- packages/ui/src/pages/Home.tsx
Using a 3 dots button everywhere, not only on Mobile.
> Remove the double settings

- packages/ui/src/components/modals/ChangeMultisig.tsx
- packages/ui/src/components/modals/ProposalSigning.tsx
- packages/ui/src/components/modals/Send.tsx
- packages/ui/src/hooks/useSigningCallback.tsx
- packages/ui/src/pages/Creation/index.tsx
- packages/ui/src/utils/extinsicErrorChecks.ts
- packages/ui/tsconfig.json
fixes #198 
Using some code from pjs/apps handling much more than the couple calls I handled so far.
I tested with batch, multisig, proxy successfully.
> Better error handling

- packages/ui/src/components/Toasts/Snackbar.tsx
> Fix Toast overlapping image

- packages/ui/src/components/modals/ProposalSigning.tsx
> Fix calldata check

- packages/ui/src/components/modals/ChangeMultisig.tsx
closes #238 
if you end up selecting the same multisig (the same signatories and same threshold) you won't be able to go "next" any more
> Prevent changing for the same multisig

- packages/ui/src/components/AccountDisplay.tsx
Fixing this where addresses aren't displayed. This slipped my checks 
Hoping it doesn't break anything else, I checked but I'm in hurry :D
> Always show the address in any case

- packages/ui/src/components/modals/ProposalSigning.tsx
- packages/ui/src/components/select/SignerSelection.tsx
- packages/ui/src/pages/Creation/Summary.tsx
> Fix label display

- packages/ui/src/pages/About.tsx
Sniped by @bkchr
https://twitter.com/bkchr/status/1681626102375014401
> Use the wording trust minimized

- packages/ui/src/components/modals/Send.tsx
- packages/ui/src/hooks/useMultisigProposalNeededFunds.tsx
closes #248 
To test, create a MSig with as signatories at least 1 account that you control but doesn't have funds. When you selected it to submit a TX it won't have enough funds (even on Rococo where the fees are ridiculous)
I tested on Polkadot too
> Show more info with needed and reserved funds

- packages/ui/src/hooks/useMultisigCallsSubscription.tsx
- packages/ui/src/hooks/useMultisigsByAccountSubscription.tsx
Attempt at closing #205
Adding some more logs and see if this works.
> Add retry subscription with error message

- packages/ui/src/components/select/GenericAccountSelection.tsx
closes https://github.com/ChainSafe/Multix/issues/286
> Fix filtering by name

- packages/ui/src/components/EasySetup/BalancesTransfer.tsx
- packages/ui/src/components/select/AccountSelection.tsx
- packages/ui/src/utils/getOptionLabel.ts
> Fix nits on send field

- README.md
- packages/ui/README.md
- squid/README.md
> Fix minor typos

- packages/ui/src/components/IdenticonBadge.tsx
- packages/ui/src/components/library/Select.tsx
> fix: solve errors from console regarding the incorrect DOM properties

- packages/ui/src/components/modals/ChangeMultisig.tsx
- packages/ui/src/pages/Creation/Summary.tsx
I left a little useless quote and `$` in the error message from  https://github.com/ChainSafe/Multix/pull/310
> Fix nit quotes

- packages/ui/src/components/select/MultiProxySelection.tsx
- packages/ui/src/hooks/useMultisigCallsSubscription.tsx
- packages/ui/src/hooks/useMultisigsBySignatoriesOrWatchedSubscription.tsx
- packages/ui/src/hooks/usePureByIdSubscription.tsx
> Fix loading when nothing to query

- .github/workflows/deploy-ui-cf-pages.yaml
- packages/ui/src/contexts/WalletConnectContext.tsx
I forgot to push the WC id to cloudflare, so it's not connecting to it in prod.
> Add WC id to clouflare deployment

- packages/ui/src/pages/Home/Home.tsx
Remove the referendum banner as it's been approved :tada:
> Remove banner for referendum

- .gitignore
- packages/ui/cypress/support/Extension.ts
- packages/ui/cypress/support/commands.ts
- packages/ui/cypress/support/page-objects/landingPage.ts
- packages/ui/cypress/support/page-objects/topMenuItems.ts
- packages/ui/cypress/tests/login.cy.ts
- packages/ui/src/components/library/Autocomplete.tsx
- packages/ui/src/components/select/MultiProxySelection.tsx
- packages/ui/src/contexts/AccountsContext.tsx
- packages/ui/src/pages/Creation/Summary.tsx
- packages/ui/src/pages/Home/Home.tsx
The test wasn't robust because the code wasn't either. It had a trick to re-trigger the connection request, which made the test flaky. It should now be cleaner, and stable
> Make account connection test robust

- packages/ui/src/components/modals/ProposalSigning.tsx
Closes #352 
- set the size of the spinner to 16px
> fix: loader size

- packages/ui/src/pages/Creation/Summary.tsx
- packages/ui/src/pages/Creation/index.tsx
> Don't show errors when submitting extrinsics

- packages/ui/src/components/NewMulisigAlert.tsx
- packages/ui/src/components/Toasts/Snackbar.tsx
- packages/ui/src/components/modals/ChangeMultisig.tsx
- packages/ui/src/components/modals/ProposalSigning.tsx
- packages/ui/src/contexts/ToastContext.tsx
- packages/ui/src/hooks/useCheckBalance.tsx
- packages/ui/src/hooks/usePureProxyCreationNeededFunds.tsx
- packages/ui/src/pages/Creation/Summary.tsx
- packages/ui/src/pages/Creation/index.tsx
closes #351 
And on top of this it
- Shows reserved amount on the summary for multisig creation and multisig changes
- Says the creation takes ~1min (it's more 30s on relay chains, but 10min
- Set errors on top of the modal overlay (see screenshot)
> Make better errors

- packages/ui/src/hooks/usePendingTx.tsx
> Fix display of who signed

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/pull_request_template.md
Hey @Tbaut, @Lykhoyda 
I put together this PR template. As mentioned in the retro, the idea is to give us a reminder at the submission stage of things we may otherwise overlook. 
Please feel free to suggest changes and add / remove any items you think are needed or unnecessary 🙏
> Add pr submission template

- packages/ui/src/components/CallInfo.tsx
bug in prod. Trying to investigate why, this stops the fire at least.
> Hotfix for pallet method undefined

- packages/ui/cypress/support/page-objects/multisigPage.ts
- packages/ui/cypress/support/page-objects/settingsPage.ts
- packages/ui/cypress/tests/watched-accounts.cy.ts
- packages/ui/src/components/Transactions/Transaction.tsx
- packages/ui/src/components/WalletConnect/WalletConnectSession.tsx
- packages/ui/src/pages/Home/Home.tsx
- packages/ui/src/pages/Settings/Settings.tsx
Related to #378
Adds new to test to ensure that
- watched accounts can see but not utilize wallet connect components
- watched accounts can see tx's in the transaction list but cannot see the review button
> More watched accounts tests

- packages/ui/src/components/WalletConnect/WalletConnectActiveSessions.tsx
- packages/ui/src/components/modals/WalletConnectSessionProposal.tsx
Prevent this crash when connecting with e.g https://lab.web3modal.com/library/wagmi/ and style the error
> Prevent crash when connecting with Walletconnect key

- packages/ui/package.json
- packages/ui/src/components/ErrorFallback/ErrorFallback.tsx
- packages/ui/src/pages/routes.tsx
- yarn.lock
closes #184
- Added a Fallback component to be shown when an error occurs on any route 
! The error design is super raw and could be improved
To try how it works you can misspell the component name
---
> feat: add error component

- packages/ui/cypress/tests/wallet-connect.cy.ts
> Basic tests for wallet connect expected state

- packages/ui/cypress/support/commands.ts
- packages/ui/cypress/tests/login.cy.ts
- packages/ui/package.json
- yarn.lock
closes #452 
there's still quite some work to be done [on the plugin's side](https://github.com/ChainSafe/cypress-polkadot-wallet) in terms of doc etc. But that's a step.
> Use the published @chainsafe/cypress-polkadot-wallet cypress plugin

- packages/ui/.env.example
- packages/ui/README.md
- packages/ui/src/constants.ts
- squid/.env.example
- squid/assets/envs/.env.asset-hub-kusama
- squid/assets/envs/.env.asset-hub-polkadot
- squid/assets/envs/.env.kusama
- squid/assets/envs/.env.polkadot
address concerns raised in #468
> Use ibp RPCs

- packages/ui/package.json
- yarn.lock
cf https://github.com/ChainSafe/Multix/pull/477
> Fix security vuln in vite and update deps

- packages/ui/src/components/AccountDisplay.tsx
- packages/ui/src/hooks/useIdentity.tsx
closes #488 
This aligns with e.g subscan
> Fix display with sub identity

- packages/ui/cypress/tests/setIdentity.cy.ts
- packages/ui/src/components/select/NetworkSelection.tsx
- packages/ui/src/constants.ts
- packages/ui/src/pages/Home/MultisigView.tsx
- packages/ui/src/utils/camelcasetoString.ts
- squid/assets/envs/.env.westend
- squid/commands.json
- squid/squid-manifests/large-squid.yaml
closes #487 
This removes Joystream that don't seem to have any usage for now and adds Westend
---
> Support Westend, remove Kilt and Joystream

- packages/ui/src/pages/Creation/NameSelection.tsx
- packages/ui/src/pages/Creation/index.tsx
> Info for name override

- packages/ui/src/components/library/Button.tsx
- packages/ui/src/components/modals/ProposalSigning.tsx
closes https://github.com/ChainSafe/Multix/issues/511
This is a relatively simple color change
> Reject as negative button

- packages/ui/src/components/AccountDisplay/AccountDisplay.tsx
the copy hover now appears gradually over 250ms
> Add animation to copy hover

- packages/ui/src/contexts/ToastContext.tsx
> fix toasts

- packages/ui/package.json
- yarn.lock
> Fix: bump cypress plugin

- packages/ui/cypress/tests/watched-accounts.cy.ts
- packages/ui/src/App.tsx
- packages/ui/src/components/EasySetup/SetIdentity.tsx
- packages/ui/src/components/modals/Send.tsx
- packages/ui/src/constants.ts
- packages/ui/src/contexts/PeopleChainApiContext.tsx
- packages/ui/src/hooks/useGetIdentity.tsx
- packages/ui/src/hooks/useHasIdentityFeature.tsx
- packages/ui/src/hooks/useHasIdentityPallet.tsx
- packages/ui/src/hooks/useIdentity.tsx
- packages/ui/src/hooks/useIdentityApi.tsx
- packages/ui/src/pages/Home/MultisigActionMenu.tsx
Addresses: https://github.com/ChainSafe/Multix/issues/543
> Fix: fix identity for chain with a People Chain (Kusama, soon Polkadot)

- packages/ui/src/constants.ts
- squid/assets/envs/.env.paseo
- squid/squid-manifests/large-squid.yaml
> Paseo prefix 0

- packages/ui/src/components/select/AccountSelection.tsx
> Watch accounts width width

- packages/ui/src/components/EasySetup/BalancesTransfer.tsx
- packages/ui/src/components/modals/ChangeMultisig.tsx
- packages/ui/src/hooks/useGetMultisigTx.tsx
- packages/ui/src/pages/Creation/index.tsx
Closes a problem with invalid checksum
> Support hydra specific calls

- packages/ui/cypress/fixtures/landingData.ts
- packages/ui/cypress/fixtures/westendAccounts.ts
- packages/ui/cypress/support/commands.ts
- packages/ui/cypress/support/page-objects/modals/hiddenAccountInfoModal.ts
- packages/ui/cypress/support/page-objects/multisigPage.ts
- packages/ui/cypress/support/page-objects/settingsPage.ts
- packages/ui/cypress/tests/hidden-accounts.cy.ts
- packages/ui/cypress/tests/name-edition-display.cy.ts
- packages/ui/cypress/tests/network-switch.cy.ts
- packages/ui/cypress/tests/watched-accounts.cy.ts
- packages/ui/src/App.tsx
- packages/ui/src/components/modals/HiddenAccountInfo.tsx
- packages/ui/src/contexts/HiddenAccountsContext.tsx
- packages/ui/src/contexts/ModalsContext.tsx
- packages/ui/src/contexts/MultiProxyContext.tsx
- packages/ui/src/hooks/useGetIdentity.tsx
- packages/ui/src/pages/Home/MultisigActionMenu.tsx
- packages/ui/src/pages/Settings/HiddenAccounts.tsx
- packages/ui/src/pages/Settings/Settings.tsx
- packages/ui/src/pages/Settings/WatchedAccounts.tsx
- packages/ui/vite.config.ts
> Allow hidding accounts

- packages/ui/cypress/support/page-objects/sendTxModal.ts
- packages/ui/cypress/tests/asset-hub-transactions-creation.cy.ts
- packages/ui/src/components/CallInfo.tsx
- packages/ui/src/components/EasySetup/BalancesTransfer.tsx
- packages/ui/src/components/TransferAsset.tsx
- packages/ui/src/components/library/AssetBalance.tsx
- packages/ui/src/components/library/Balance.tsx
- packages/ui/src/components/library/Button.tsx
- packages/ui/src/hooks/useGetAssetBalances.tsx
> Asset batch for multisend 

- packages/ui/cypress/tests/address-bar.cy.ts
- packages/ui/cypress/tests/hidden-accounts.cy.ts
- packages/ui/cypress/tests/transactions.cy.ts
- packages/ui/cypress/tests/watched-accounts.cy.ts
- packages/ui/src/hooks/useDisplayError.tsx
closes https://github.com/ChainSafe/Multix/issues/639
> Fix landing experience when not connected and landing with an address in the url

- packages/ui/.eslintrc
- packages/ui/cypress/tests/balances-transfer-batch-multi-asset.cy.ts
- packages/ui/cypress/tests/transactions.cy.ts
- packages/ui/cypress/tests/watched-accounts.cy.ts
- packages/ui/package.json
- packages/ui/src/components/CallInfo.tsx
- packages/ui/src/components/TransferAsset.tsx
- packages/ui/src/hooks/useAccountDisplayInfo.tsx
- packages/ui/src/hooks/useGetBalance.tsx
- packages/ui/src/hooks/useGetEncodedAddress.tsx
- yarn.lock
the title says it all.
Also fixes a bug when transferable balance is <0
> Enhance tests and add Polimec vested transfer

- packages/ui/src/components/modals/ChangeMultisig.tsx
- packages/ui/src/components/modals/ProposalSigning.tsx
- packages/ui/src/components/modals/Send.tsx
- packages/ui/src/components/modals/WalletConnectSigning.tsx
- packages/ui/src/hooks/usePendingTx.tsx
- packages/ui/src/hooks/useSigningCallback.tsx
- packages/ui/src/pages/Creation/Summary.tsx
- packages/ui/src/pages/Creation/index.tsx
- packages/ui/src/utils/translateError.ts
Applying fix suggested to prevent this issue: https://github.com/polkadot-api/polkadot-api/issues/958
> Fix Bad Proof error when sending transactions

- packages/ui/src/constants.ts
> Use Lucky friday RPC first

- packages/ui/src/constants.ts
- packages/ui/src/contexts/PendingTxContext.tsx
> Remove metadata versionning check and use the latest

- packages/ui/src/components/CallInfo.tsx
- packages/ui/src/components/Transactions/Transaction.tsx
- packages/ui/src/components/Transactions/TransactionList.tsx
- packages/ui/src/constants.ts
- packages/ui/src/contexts/ApiContext.tsx
- packages/ui/src/contexts/PendingTxContext.tsx
- packages/ui/src/contexts/PeopleChainApiContext.tsx
- packages/ui/src/utils/wsStatusChangeCallback.ts
- use Kusama RPCs that support archive queries
- do not show decoded Txs on the overview when the calldata is > 1KB
- show in the console which RPC we're using and the connection status
> Fix kusama rpcs

- packages/ui/src/utils/jsonPrint.ts
> Print hex if not ascii

- packages/ui/.papi/polkadot-api.json
- packages/ui/src/constants.ts
- squid/assets/envs/.env.dancelight
- squid/assets/envs/.env.tanssi
Updates Tanssi endpoints to the latest production version.
---
> Updates Tanssi related endpoints
