ui/src/components/modals/Send.tsx, ui/src/contexts/MultiProxyContext.tsx
There is no more automatic naming. This was a bad idea after all :)
closes #42 
closes #41
=> No more automatic renaming

ui/src/components/modals/ChangeMultisig.tsx, ui/src/hooks/useSigningCallback.tsx, ui/src/pages/Creation/Summary.tsx
closes #37 
Here's how you can get the error:
- initiate a multisig rotation, go through both calls, it should work.
- don't approve/reject any proposal and initiate the exact same rotation.
- if you reject the first addProxy proposal, you should be able to re-initiate the same multisig rotation, the first call should work, the second should fail with a nice error message.
=> Better error handling on multisig rotation

ui/src/components/AccountDisplay.tsx, ui/src/components/IdentityIcon.tsx, ui/src/theme.ts
closes #103 
ready to review for a first pass, but still something to do: Use the identity name in the selection dropdown, or anywhere we think it's needed.
@Lykhoyda this is one of the instance where I had to either use either sx, or a styled component, otherwise I don't have access to the DOM node to style it, because it's appended dynamically at the end of the DOM, it's not inside my styled component.
To test, you need to set an identity (e.g you can do this with pjs/apps) https://wiki.polkadot.network/docs/learn-identity
Here's a watch mode on the ChaosDAO where all members have an identity set.
alternatively, if you want to see this too, you need to
- point your local node at Kusama (see the .env.example comments in ./squid)
- connect the UI to it using ?network=local
- add a hacky …
=> Show identity and info on hover/touch

packages/squid/schema.graphql, packages/squid/src/model/generated/_proxyType.ts, packages/squid/src/util/getProxyInfoFromArgs.ts, packages/squid/src/util/getProxyTypeFromRaw.ts, packages/squid/src/util/getPureProxyInfoFromArgs.ts
any proxy type that is not supported will be displayed as "Unknown" now, instead of crashing the indexer
=> Prevent indexer crash for new unsupported proxy types

packages/ui/src/contexts/MultiProxyContext.tsx
hot fix for live issue.
The UI shows accounts from the last network on network change, if the new network doesn't have any account.
=> Refresh account list even if no account

packages/ui/src/hooks/usePendingTx.tsx
This is a temporary (but not hacky) fix for something that should never happen. The on-chain data is returning proposals for other multisigs than the ones we requested the info for.
https://github.com/polkadot-js/apps/issues/9103
=> Fix phantom proposals

packages/ui/src/components/AccountDisplay.tsx, packages/ui/src/components/modals/ChangeMultisig.tsx, packages/ui/src/contexts/AccountNamesContext.tsx, packages/ui/src/contexts/AccountsContext.tsx, packages/ui/src/pages/Creation/index.tsx
Polkadot has prefix 0. After https://github.com/ChainSafe/Multix/pull/177 was merged with re-encoding, things broke because of the checks for `chainInfo?.ss58Format`
=> Fix chainInfo for Polkadot

packages/ui/src/components/AccountDisplay.tsx, packages/ui/src/components/modals/ChangeMultisig.tsx, packages/ui/src/contexts/AccountsContext.tsx, packages/ui/src/contexts/WatchedAddressesContext.tsx, packages/ui/src/pages/Creation/index.tsx, packages/ui/src/utils/encodeAccounts.ts, packages/ui/src/utils/namesUtil.ts, packages/ui/src/utils/reEncodeInjectedAccounts.ts
If using an evm address, the encoding is throwing. We needed to handle this case in a catch accordingly.
this happens when on using Talisman, you have an EVM account and tick the box "show evm account".
=> Hotfix encoding evm crash

packages/ui/src/components/Toasts/ToastBar.tsx
An issue was reported to me by @freddyli7 but the error must have disappeared before he came back to Multix. As a result, it was hard to know, what went wrong unless you go check subscan (and because it's a multisig extrinsic, this isn't easy either).
I had removed this behavior because I thought it was annoying to users, it turns out that since it's rather an exception, bothering users and asking them to manually close the error isn't that annoying either and may actually help them.
=> Never hide errors

packages/ui/src/components/Toasts/Snackbar.tsx
This issue happens when you have many proposals in the queue, and not a large (high) screen.
Then the toasts show up in the middle of the screen instead of the bottom.
=> Fix toasts not displayed at the bottom

packages/ui/src/components/NewMulisigAlert.tsx, packages/ui/src/pages/Creation/index.tsx, packages/ui/src/pages/Home.tsx
- disable the create button and add loader upon signing the multisig creation
- show a watched account if the extension is connected but no account is shared and the watched account has multisigs
- move from h1 (super big) to h3  error message if no account connected and no watched account
- In case your first account ever was created, you'd have the waiting screen, and the info alert afterward still. This fixes it.
=> Better onboading experience

packages/ui/src/components/IdenticonBadge.tsx, packages/ui/src/components/Toasts/ToastContent.tsx, packages/ui/src/components/Transactions/Transaction.tsx, packages/ui/src/components/Transactions/TransactionList.tsx, packages/ui/src/components/library/Button.tsx, packages/ui/src/components/library/InputField.tsx, packages/ui/src/components/library/TextFieldStyled.tsx, packages/ui/src/components/modals/ProposalSigning.tsx, packages/ui/src/components/modals/Send.tsx, packages/ui/src/pages/Creation/index.tsx, packages/ui/src/pages/Home.tsx, packages/ui/src/styles/App.css, packages/ui/src/styles/theme.ts
=> add color palette

packages/ui/src/contexts/MultiProxyContext.tsx, packages/ui/src/pages/Help/index.tsx
closes #227 
- if watching a pure, and the signatory of a multisig, one multisig was duplicated
- another unrelated bug would be showing the 1st multisig twice in the help page
To replicate, watch the following on Kusama:
- Alice u Bob `DGaHm71gRHJGQVF2ubunkx37qgLpno2gYibq2WHoDJpFMt6`
- Chaos Dao Pure proxy `DCZyhphXsRLcW84G9WmWEXtAA8DKGtVGSFZLJYty8Ajjyfa`
=> Fix duplicate multisigs

packages/ui/src/components/library/ModalCloseButton.tsx, packages/ui/src/components/modals/ChangeMultisig.tsx, packages/ui/src/components/modals/EditNames.tsx, packages/ui/src/components/modals/ProposalSigning.tsx, packages/ui/src/components/modals/Send.tsx, packages/ui/src/hooks/useSigningCallback.tsx
- rename the close button to ModalCloseButton because it's specifically styled.
- remove the close button when there's an error in the multisig change. To see this, make the same Tx twice to change a multisig (signatory rotation)
- delete stray console.log
=> Close button modal nits

packages/ui/src/components/IdenticonBadge.tsx, packages/ui/src/components/Transactions/Transaction.tsx, packages/ui/src/components/library/Autocomplete.tsx, packages/ui/src/components/library/Button.tsx, packages/ui/src/components/library/InputField.tsx, packages/ui/src/components/library/Select.tsx, packages/ui/src/components/library/TextFieldLargeStyled.tsx, packages/ui/src/styles/theme.ts
=> fix border-radius

packages/ui/src/components/IdentityIcon.tsx
Due to the change of icon, the new ones didn't support the forwardref, and there was no tooltip displayed.
=> Fix identity popup

packages/ui/src/pages/Home.tsx
I don't remember how we broke this, but it sounds old.
We were not showing the the option menu for multisigs without proxy.
What I tested:
- watched accounts (multisig or proxy) have no send button
- watched accounts (multisig or proxy) have an option menu to change names
- owned accounts (multisig or proxy) have a send button
=> Hot fix - option button for multisig without pure proxy

packages/ui/src/App.tsx, packages/ui/src/contexts/ModalsContext.tsx, packages/ui/src/pages/Home.tsx
This is a small refactoring to set the stage for #136 
It's taking elements from #273 but only changes the logic of opening/closing the modals. Nothing should change beside the fact that it'll fix the issue that modals get closed if the list of multisig is refreshing.
=> Add modal context

packages/ui/src/contexts/MultiProxyContext.tsx
I was told on Hydra that this account was a multisig and not showing on Multix `7NJp5SL8d2SGhzwqdD7qnF4Z3VQe4uMefoxWFnQMuGJeLwPw`
I could verify and found the issue. The reason is that this account was delegatee for a non-pure proxy, and my logic had no case for it.
=> Show multisig if they are delegatee for non pure proxies

packages/ui/src/constants.ts
Khala has been notoriously slow to sync (>12h compared to <30min for all the others) when a new deployment was made, preventing us from deploying quickly.
While it's not impacted by most of the changes, I moved it to its own processor so that we can deploy quicker.
=> Move khala to own processor

packages/ui/src/components/AccountDisplay.tsx, packages/ui/src/components/EasySetup/BalancesTransfer.tsx, packages/ui/src/components/EasySetup/FromCallData.tsx, packages/ui/src/components/EasySetup/ManualExtrinsic.tsx, packages/ui/src/components/Transactions/TransactionList.tsx, packages/ui/src/components/modals/ChangeMultisig.tsx, packages/ui/src/components/modals/ProposalSigning.tsx, packages/ui/src/components/modals/Send.tsx, packages/ui/src/contexts/ApiContext.tsx, packages/ui/src/hooks/useCallInfoFromCallData.tsx, packages/ui/src/hooks/useGetBalance.tsx, packages/ui/src/hooks/useMultisigProposalNeededFunds.tsx, packages/ui/src/hooks/usePendingTx.tsx, packages/ui/src/hooks/useProxyAdditionNeededFunds.tsx, packages/ui/src/hooks/usePureProxyCreationNeededFunds.tsx, packages/ui/src/pages/Creation/index.tsx, packages/ui/src/pages/Home/Home.tsx
closes #243 
I removed the fact that we have to check for both `isApiReady` and `api` to be defined. Makes it for a clearer code.
=> Refactor api context and fix network switching issue

packages/ui/src/components/modals/ChangeMultisig.tsx, packages/ui/src/pages/Creation/Summary.tsx, packages/ui/src/pages/Creation/ThresholdSelection.tsx, packages/ui/src/pages/Creation/WitProxySelection.tsx, packages/ui/src/pages/Creation/index.tsx
closes https://github.com/ChainSafe/Multix/issues/276
We now add a checkbox in the multisig creation flow for user to choose wether they want a proxy or not. It's checked by default, and won't be visible for chains that don't have the proxy pallet.
Because there's actually nothing to do to create such a simple multisig, what we do is propose to create a system remark, which is super cheap and contains "Multix creation [address]". We need to have at least 1 on-chain transaction from the multisig in order for the indexer to pick it up and know about this new multisig.
Whether this transaction is approved or not is actually irrelevant.. it just shows users what it's like to have a multisig transaction pending then :man_shrugging:
=> Support chains without a proxy

packages/ui/src/components/Drawer/DrawerMenu.tsx, packages/ui/src/components/Header/Header.tsx, packages/ui/src/components/library/Link.tsx, packages/ui/src/components/library/index.tsx, packages/ui/src/pages/routes.tsx, packages/ui/src/styles/theme.ts
Closes #302 
- add NavLink component
- Replaced RouterLink in Navbar
- Update mobile navigation
- Re-arrange nav links (About in the end)
=> feat: update navbar active link

package.json, packages/ui/cypress/fixtures/knownMultisigs.ts, packages/ui/cypress/support/commands.ts, packages/ui/cypress/tests/transactions.cy.ts, packages/ui/cypress/utils/rejectCurrentMultisigTxs.ts, packages/ui/src/hooks/useGetEncodedAddress.tsx, packages/ui/src/hooks/usePendingTx.tsx, yarn.lock
closes #370 
I had to se the following in the resolutions
```
"@polkadot/util-crypto": "12.5.1",
"@polkadot/util": "12.5.1"
```
because `@polkadot/api` (not updated in 2 months) was requesting another version, and this led to conflicts.
=> Helper function to reject any pending tx

packages/ui/src/components/library/Select.tsx, packages/ui/src/components/modals/Send.tsx, packages/ui/src/components/select/NetworkSelection.tsx
Came across the `as SelectChangeEvent<string>` in the code and thought we could do better. It ended up still adding more code than what we had, but it's a little nicer and more generic I think. wdyt @Lykhoyda?
=> Small refactor to prevent casting selected value.

packages/ui/src/components/ConnectOrWatch.tsx, packages/ui/src/components/Drawer/DrawerMenu.tsx, packages/ui/src/components/Header/Header.tsx, packages/ui/src/components/library/Select.tsx, packages/ui/src/components/modals/Send.tsx, packages/ui/src/components/select/MultiProxySelection.tsx, packages/ui/src/components/select/NetworkSelection.tsx, packages/ui/src/constants.ts
Closes #264 
- Updated the network selection for the desktop
- Updated the network selection for mobile
- Mobile menu style updates
- fix "watch account" or "connect" for mobile devices
- fix loader appearance for MultiProxy selection when there is no proxy
=> feat: Update network select

packages/ui/src/components/CallInfo.tsx, packages/ui/src/components/EasySetup/FromCallData.tsx
Hotfix for a bug in prod... because of `any` :roll_eyes: 
With for instance `0x1a00181400c502008500042c0f5205000000000000000000001400c902000500042c0f5205000000000000000000001400cd02008500042c0f5205000000000000000000001400d102008500042c0f5205000000000000000000001400d502008500042c0f5205000000000000000000001400d902008500042c0f520500000000000000000000`
We had
=> Fix value is null

packages/ui/src/components/CallInfo.tsx, packages/ui/src/components/EasySetup/FromCallData.tsx
Follow-up to https://github.com/ChainSafe/Multix/pull/399
Things like the following where not displayed nicely (in the tx list, not in the "from call data" because or the removal of the `proxy.proxy`) and a bunch of errors were fired in the console. 
`0x1e00004e899a75c0571af8e2721e8d4c7cfe2206c0e63bc1db88b3e7ef69846d1591720018000c0407004e899a75c0571af8e2721e8d4c7cfe2206c0e63bc1db88b3e7ef69846d1591720b00b04e2bde6f0000187365636f6e640000146f74686572`
=> Handle RuntimeCall the same way as Vec<RuntimeCall> 

packages/ui/cypress/tests/login.cy.ts, packages/ui/cypress/tests/transactions.cy.ts, packages/ui/cypress/utils/clickOnConnect.ts
=> Small refactor with clickOnConnect test function

packages/ui/cypress/fixtures/watchAccounts/watchMultisigs.ts, packages/ui/cypress/fixtures/watchAccounts/watchSignatories.ts
Realized that one of the signatories in the test fixtures had the incorrect address for the mnemonic being specified. 
Rotated in the account for the mnemonic here (then updated the other fixture with the new multisig address).
=> Update test fixtures for watched account tests

packages/ui/cypress/tests/transactions.cy.ts, packages/ui/src/components/CallInfo.tsx, packages/ui/src/components/EasySetup/BalancesTransfer.tsx, packages/ui/src/hooks/useAccountBaseFromAccountList.tsx
closes #395 
How to test:
In New tx > Send tokens
In the "to" field you'll have the addresses from your name registry too.
=> Use name registry in recipients list

packages/ui/src/contexts/MultiProxyContext.tsx, packages/ui/src/hooks/useDisplayError.tsx, packages/ui/src/hooks/useMultisigCallsSubscription.tsx, packages/ui/src/hooks/useMultisigsBySignatoriesOrWatchedSubscription.tsx, packages/ui/src/hooks/usePureByIdSubscription.tsx
related to #400 
After exploring many other potential issues this could come from (generally more complex as well), I'm exploring one that could be the automatic refresh that can't be stopped and could actually spam our server.
I'm therefore removing the auto-refresh that I implemented a while ago, and add a better copy + reconnect button that hopefully makes the life of the couple affected persons better than previously. We will see if the spikes of demand on the server ever decrease. It's a shot in the dark unfortunately.
To test and see the error, change in `constants.ts` the `wsGraphqlUrl` of a network to point to v6 (it's offline) instead of v7, and visit this network.
=> Manual reconnect button

packages/ui/src/constants.ts, squid/squid-manifests/large-squid.yaml
closes #441 
The phala team is now using a new endpoint, after the previous testnet was bricked.
This is already deployed and can be tested live.
=> Use Rhala on rococo

packages/ui/src/components/select/NetworkSelection.tsx
closes #443 
As a Joystream element is alone in the list, It weirdly splits the element into two columns in Safari. Added the fix for one network in the list.
=> fix: menu item wrong displaying in Safari

packages/ui/cypress/support/page-objects/topMenuItems.ts, packages/ui/cypress/tests/network-switch.cy.ts, packages/ui/cypress/utils/clickOnConnect.ts, packages/ui/src/components/LoadingBox.tsx, packages/ui/src/components/select/MultiProxySelection.tsx, packages/ui/src/contexts/MultiProxyContext.tsx, packages/ui/src/hooks/useDisplayLoader.tsx, packages/ui/src/hooks/useMultisigsBySignatoriesOrWatchedSubscription.tsx, packages/ui/src/pages/Overview/index.tsx
closes #387
- Fixes UI jump during multisig switch 
- The loader is not shown anymore for the multiproxy selector
- Overview page has loading status during multisigs fetching
---
=> fix: menu jump during multisig switch

packages/ui/cypress/support/page-objects/topMenuItems.ts, packages/ui/cypress/tests/address-bar.cy.ts, packages/ui/cypress/tests/network-switch.cy.ts, packages/ui/cypress/tests/setIdentity.cy.ts, packages/ui/cypress/tests/watched-accounts.cy.ts, packages/ui/src/components/Drawer/DrawerMenu.tsx, packages/ui/src/components/Header/Header.tsx, packages/ui/src/components/select/MultiProxySelection.tsx
=> Differenciate desktop and mobile to clean up tests

packages/ui/cypress/support/page-objects/components/accountDisplay.ts, packages/ui/cypress/tests/multisig-creation.cy.ts, packages/ui/cypress/tests/walletconnect.cy.ts, packages/ui/cypress/tests/watched-accounts.cy.ts, packages/ui/src/components/IdenticonBadge.tsx, packages/ui/src/contexts/MultiProxyContext.tsx
closes #176 
Not 100% convinced as this kinds of hides a good part of the identicon.. but on the other hand, we're talking about watched accounts.. so it's not that important.
---
=> Show watch indicator

chopsticks-config.yml, packages/ui/cypress/fixtures/setIdentity/setIdentityMultisigs.ts, packages/ui/cypress/fixtures/setIdentity/setIdentitySignatories.ts, packages/ui/cypress/tests/setIdentity.cy.ts
Rococo removed the identity pallet. We now do the test on Polkadot, that still has it.
=> Fix identity test

packages/ui/src/components/EasySetup/ManualExtrinsic.tsx
When there's only 1 param in the extrinsic, e.g beefy.setNewGenesis. If you type 1 number for instance (valid) you'll still get a meaningless error.
This has other repercussions, so that if you do on Polkadot `staking.bondExtra` the number of DOT won't be multiplied by  10^decimals :roll_eyes:
=> Fix erroneous error in Manual Extrinsic

packages/ui/src/components/WalletConnect/WalletConnectActiveSessions.tsx, packages/ui/src/components/modals/WalletConnectSessionProposal.tsx, packages/ui/src/hooks/useWalletConnectEventsManager.ts
Although the events aren't formerly supported (account change and disconnect, to be supported in another PR see https://github.com/ChainSafe/Multix/issues/483) this will make sure that the connection is actually working and doesn't crash.
I updated [the wiki](https://github.com/ChainSafe/Multix/wiki/Connect-Dapps-to-Multix-using-WalletConnect-v2) with up to date images.
=> Hotfix for WalletConnect connection

packages/ui/src/utils/getErrorMessageReservedFunds.tsx
We were showing a $ sign in front of an amount of DOT.
=> Fix: dollar typo

packages/ui/src/components/AccountDisplay/AccountDisplay.tsx, packages/ui/src/components/DeepTxAlert.tsx, packages/ui/src/components/MultisigCompactDisplay.tsx, packages/ui/src/components/Transactions/TransactionProgress.tsx, packages/ui/src/components/modals/ChangeMultisig.tsx, packages/ui/src/components/modals/WalletConnectSessionProposal.tsx, packages/ui/src/pages/Creation/Summary.tsx, packages/ui/src/pages/Home/HeaderView.tsx, packages/ui/src/pages/Home/MultisigAccordion.tsx, packages/ui/src/pages/Home/MultisigView.tsx, packages/ui/src/pages/Overview/CustomNode.tsx, packages/ui/src/pages/Overview/index.tsx, packages/ui/src/pages/Settings/WatchedAccounts.tsx, packages/ui/src/utils/copyToClipboard.ts
closes https://github.com/ChainSafe/Multix/issues/489
I went for the hover + copy tooltip
- so as to avoid having yet another icon (on top of the edit one)
- because our primary target is desktop and this is better than nothing, also mobile users may also figure it out (the tooltip will help)
The edge-cases here are in the dropdown menus where this function shouldn't be enabled.
I'd appreciate a check in browser I don't have access to such as Safari @asnaith and on mobile :pray
https://github.com/ChainSafe/Multix/assets/33178835/e209f8c4-8b92-46be-b69d-95d091ce744d
---
=> Enable copy address on click

chopsticks-config.yml, packages/ui/cypress/support/page-objects/landingPage.ts, packages/ui/cypress/tests/address-bar.cy.ts, packages/ui/cypress/tests/multisig-creation.cy.ts, packages/ui/cypress/utils/waitForMultisigLength.ts, packages/ui/src/components/AccountDisplay/AccountDisplay.tsx, packages/ui/src/components/DeepTxAlert.tsx, packages/ui/src/components/NewMulisigAlert.tsx, packages/ui/src/components/select/NetworkSelection.tsx, packages/ui/src/constants.ts, squid/squid-manifests/large-squid.yaml
- remove indexer logs
- remove Kilt indexer until someone says they want it
- fix copy tooltip not disappearing
- remove cy.clock that's useless in tests and close the banner manually instead
- silences a warning in the console
=> Various UI and test fixes

packages/ui/src/components/WalletConnect/WalletConnectActiveSessions.tsx, packages/ui/src/components/modals/WalletConnectSessionProposal.tsx
closes https://github.com/ChainSafe/Multix/issues/541
Hydration wan't passing any required namespace any more and has everything in optional namespaces..
The WalletConnect doc says all fields are optional, so we just check that our current connected network is part of the list, and we go on with that.
In the mean time, we'll support both, and won't error out if only the optional is passed.
=> fix: hydra walletconnect

packages/ui/src/components/CallInfo.tsx
=> Fix: show boolean values in call

packages/ui/src/components/CallInfo.tsx, packages/ui/src/components/modals/WalletConnectSessionProposal.tsx, packages/ui/src/components/modals/WalletConnectSigning.tsx, squid/assets/envs/.env.chopsticks-ci, squid/assets/envs/.env.chopsticks-local
=> Check wc account and network

packages/ui/src/components/CallInfo.tsx, packages/ui/src/utils/jsonPrint.ts
Close an issue happening with calls with no params. E.g `staking.chill`
=> Support calls with no params

packages/ui/cypress/tests/multisig-creation.cy.ts, packages/ui/package.json, packages/ui/src/components/CallInfo.tsx, packages/ui/src/components/EasySetup/FromCallData.tsx, packages/ui/src/components/library/TextFieldStyled.tsx, packages/ui/src/hooks/useGetMultisigTx.tsx, packages/ui/src/pages/Creation/WithProxySelection.tsx, packages/ui/src/pages/Creation/index.tsx, packages/ui/src/utils/getPapiHowLink.ts, yarn.lock
- link to papi console in "From calldata"
- show error if invalid calldata
- support `tokens.transfer` whitelist on hydration
- proxy not the default any more
- more info regarding pure proxies with a wiki article + link
=> Various enhancements

packages/ui/src/components/EasySetup/FromCallData.tsx, packages/ui/src/components/modals/Send.tsx
=> Filter proxy only for the currently selected pure
